# Numpy

In [6]:
import numpy as np

In [7]:
np.__version__


'2.2.6'

In [10]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [12]:
type(my_list)

list

In [14]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [15]:
print(type(arr)) # nd stands for multidimensional array

<class 'numpy.ndarray'>


In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
np.arange(20,10) # Always remember 1st arg is less than 2nd argument

array([], dtype=int64)

In [21]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [22]:
np.zeros(5) #parameter tuning

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros(5 , dtype=int) # hyperparameter tuning  # id array

array([0, 0, 0, 0, 0])

In [24]:
np.zeros([2,2]) # 2d array

array([[0., 0.],
       [0., 0.]])

In [25]:
np.zeros([5,4]) # nd array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones(2)

array([1., 1.])

In [29]:
np.ones(2, dtype=int)

array([1, 1])

In [30]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [31]:
np.ones([4,5]) # 4 is rows nd 5 is columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
arr

array([0, 1, 2, 3, 4, 5])

In [33]:
rand(3,2)

NameError: name 'rand' is not defined

In [34]:
import random as rand

In [35]:
rand(3,2)

TypeError: 'module' object is not callable. Did you mean: 'random.random(...)'?

In [36]:
random.rand(3,2)

NameError: name 'random' is not defined

In [39]:
np.random.rand(3,2)
 # numbers are changing everytime you execute

array([[0.82812192, 0.68266423],
       [0.24465356, 0.13900743],
       [0.00362725, 0.08335215]])

In [43]:
np.random.rand(3)

array([0.1563593 , 0.32040588, 0.78109604])

In [45]:
np.random.randint(4,6)

4

In [49]:
np.random.randint(0,10)

8

In [54]:
np.random.randint(0,10,5)

array([3, 1, 7, 7, 5], dtype=int32)

In [61]:
n = np.random.randint(10,40,(8,10))
n

array([[11, 11, 16, 32, 17, 29, 14, 10, 24, 10],
       [19, 28, 25, 39, 12, 37, 21, 30, 20, 30],
       [23, 21, 32, 24, 24, 37, 34, 14, 22, 32],
       [22, 11, 29, 19, 26, 15, 23, 30, 29, 19],
       [36, 25, 15, 35, 18, 33, 28, 39, 13, 21],
       [38, 23, 26, 37, 20, 21, 32, 26, 29, 26],
       [28, 32, 32, 31, 14, 30, 14, 21, 38, 22],
       [21, 34, 37, 19, 28, 33, 34, 10, 30, 38]], dtype=int32)

In [63]:
n[5]

array([38, 23, 26, 37, 20, 21, 32, 26, 29, 26], dtype=int32)

In [64]:
n

array([[11, 11, 16, 32, 17, 29, 14, 10, 24, 10],
       [19, 28, 25, 39, 12, 37, 21, 30, 20, 30],
       [23, 21, 32, 24, 24, 37, 34, 14, 22, 32],
       [22, 11, 29, 19, 26, 15, 23, 30, 29, 19],
       [36, 25, 15, 35, 18, 33, 28, 39, 13, 21],
       [38, 23, 26, 37, 20, 21, 32, 26, 29, 26],
       [28, 32, 32, 31, 14, 30, 14, 21, 38, 22],
       [21, 34, 37, 19, 28, 33, 34, 10, 30, 38]], dtype=int32)

In [65]:
n[0:6]

array([[11, 11, 16, 32, 17, 29, 14, 10, 24, 10],
       [19, 28, 25, 39, 12, 37, 21, 30, 20, 30],
       [23, 21, 32, 24, 24, 37, 34, 14, 22, 32],
       [22, 11, 29, 19, 26, 15, 23, 30, 29, 19],
       [36, 25, 15, 35, 18, 33, 28, 39, 13, 21],
       [38, 23, 26, 37, 20, 21, 32, 26, 29, 26]], dtype=int32)

In [67]:
n

array([[11, 11, 16, 32, 17, 29, 14, 10, 24, 10],
       [19, 28, 25, 39, 12, 37, 21, 30, 20, 30],
       [23, 21, 32, 24, 24, 37, 34, 14, 22, 32],
       [22, 11, 29, 19, 26, 15, 23, 30, 29, 19],
       [36, 25, 15, 35, 18, 33, 28, 39, 13, 21],
       [38, 23, 26, 37, 20, 21, 32, 26, 29, 26],
       [28, 32, 32, 31, 14, 30, 14, 21, 38, 22],
       [21, 34, 37, 19, 28, 33, 34, 10, 30, 38]], dtype=int32)

In [66]:
n[::-1]

array([[21, 34, 37, 19, 28, 33, 34, 10, 30, 38],
       [28, 32, 32, 31, 14, 30, 14, 21, 38, 22],
       [38, 23, 26, 37, 20, 21, 32, 26, 29, 26],
       [36, 25, 15, 35, 18, 33, 28, 39, 13, 21],
       [22, 11, 29, 19, 26, 15, 23, 30, 29, 19],
       [23, 21, 32, 24, 24, 37, 34, 14, 22, 32],
       [19, 28, 25, 39, 12, 37, 21, 30, 20, 30],
       [11, 11, 16, 32, 17, 29, 14, 10, 24, 10]], dtype=int32)

In [68]:
n[::1]

array([[11, 11, 16, 32, 17, 29, 14, 10, 24, 10],
       [19, 28, 25, 39, 12, 37, 21, 30, 20, 30],
       [23, 21, 32, 24, 24, 37, 34, 14, 22, 32],
       [22, 11, 29, 19, 26, 15, 23, 30, 29, 19],
       [36, 25, 15, 35, 18, 33, 28, 39, 13, 21],
       [38, 23, 26, 37, 20, 21, 32, 26, 29, 26],
       [28, 32, 32, 31, 14, 30, 14, 21, 38, 22],
       [21, 34, 37, 19, 28, 33, 34, 10, 30, 38]], dtype=int32)

In [69]:
n[::2]

array([[11, 11, 16, 32, 17, 29, 14, 10, 24, 10],
       [23, 21, 32, 24, 24, 37, 34, 14, 22, 32],
       [36, 25, 15, 35, 18, 33, 28, 39, 13, 21],
       [28, 32, 32, 31, 14, 30, 14, 21, 38, 22]], dtype=int32)

In [70]:
n[0]

array([11, 11, 16, 32, 17, 29, 14, 10, 24, 10], dtype=int32)

In [71]:
n


array([[11, 11, 16, 32, 17, 29, 14, 10, 24, 10],
       [19, 28, 25, 39, 12, 37, 21, 30, 20, 30],
       [23, 21, 32, 24, 24, 37, 34, 14, 22, 32],
       [22, 11, 29, 19, 26, 15, 23, 30, 29, 19],
       [36, 25, 15, 35, 18, 33, 28, 39, 13, 21],
       [38, 23, 26, 37, 20, 21, 32, 26, 29, 26],
       [28, 32, 32, 31, 14, 30, 14, 21, 38, 22],
       [21, 34, 37, 19, 28, 33, 34, 10, 30, 38]], dtype=int32)

In [73]:
n[0:5]

array([[11, 11, 16, 32, 17, 29, 14, 10, 24, 10],
       [19, 28, 25, 39, 12, 37, 21, 30, 20, 30],
       [23, 21, 32, 24, 24, 37, 34, 14, 22, 32],
       [22, 11, 29, 19, 26, 15, 23, 30, 29, 19],
       [36, 25, 15, 35, 18, 33, 28, 39, 13, 21]], dtype=int32)

In [74]:
n[0,5]

np.int32(29)

In [78]:
print(n[5,-3])

26


In [79]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [82]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)