# Numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

In [3]:
import sys 
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

# Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list) 

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [10]:
np. # we learn important function 

SyntaxError: invalid syntax (1655120754.py, line 1)

In [11]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(3.0)  

array([0., 1., 2.])

In [13]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [17]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [20]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [21]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [22]:
np.arange(10,10) 

array([], dtype=int64)

In [23]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

In [ ]:
np.arange(0,10,3)

In [ ]:
np.arange(10,30,5,8)

In [ ]:
np.zeros(3) # parameter  tunning 

In [ ]:
np.zeros(5, dtype=int) # hyperparameter tunning 

In [ ]:
np.zeros((2,2), dtype=int)

In [24]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [25]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [26]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [30]:
np.zeros((5,10)) # bydefaul 1 arg -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [33]:
n

(6, 7)

In [34]:
n1

(6, 8)

In [35]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [38]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
n

(6, 7)

In [40]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [41]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
np.twos((2,3)) 

AttributeError: module 'numpy' has no attribute 'twos'

In [43]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [44]:
np.ones(2)

array([1., 1.])

In [45]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [47]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [48]:
range(5)

range(0, 5)

In [49]:
r = range(5)
r

range(0, 5)

In [50]:
for i in r:
    print(i)

0
1
2
3
4


In [51]:
list(range(5))

[0, 1, 2, 3, 4]

In [52]:
range(1,10)

range(1, 10)

In [53]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
list(range(1,10,3))

[1, 4, 7]

In [55]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [56]:
rand(3,2)

NameError: name 'rand' is not defined

In [57]:
np.random.rand(5)

array([0.14434819, 0.90497326, 0.11483213, 0.85688585, 0.72600617])

In [58]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [ ]:
np.random.rand(2,4)

In [59]:
np.random.randint(2,4)

3

In [60]:
np.random.randint(2,20) # 2nd argument is exlusive

12

In [61]:
np.random.randint(0,1) 

0

In [62]:
np.random.randint(10,20,5)

array([18, 16, 11, 12, 10], dtype=int32)

In [63]:
np.random.randint(1,6,4)

array([5, 2, 5, 2], dtype=int32)

In [64]:
np.random.rand(3)

array([0.01651347, 0.33254656, 0.09578971])

In [65]:
np.random.randint(1)

0

In [66]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [67]:
np.random.randint(-30,20,10) 

array([-18, -23, -25,   1,   6,  11, -20,   9, -11,   1], dtype=int32)

In [68]:
np.random.randint(20,30,10) 

array([22, 26, 28, 21, 23, 20, 26, 27, 22, 22], dtype=int32)

In [69]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

6

In [70]:
np.random.randint(10,21,3)

array([20, 11, 18], dtype=int32)

In [71]:
np.random.randint(1,12,10)

array([ 6,  6,  7,  3,  2,  2, 10, 10,  5, 11], dtype=int32)

In [72]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[17, 27, 21, 33, 25, 33, 11, 23, 32, 28],
       [14, 31, 19, 15, 22, 23, 12, 13, 14, 15],
       [12, 14, 38, 20, 32, 37, 21, 38, 12, 30],
       [25, 12, 35, 30, 29, 16, 23, 19, 39, 13],
       [15, 13, 37, 19, 38, 36, 28, 15, 10, 29],
       [34, 36, 27, 20, 26, 28, 33, 38, 29, 31],
       [25, 39, 27, 28, 31, 23, 15, 11, 36, 19],
       [32, 14, 30, 35, 28, 16, 37, 20, 32, 39],
       [35, 29, 25, 22, 20, 22, 10, 34, 11, 28],
       [34, 13, 29, 18, 24, 25, 13, 10, 11, 23]], dtype=int32)

In [73]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[51, 77,  9, 60, 54, 12, 34, 69, 90, 79, 99, 26],
       [56, 11, 87, 35, 35, 76, 48, 83, 50, 55, 98, 43],
       [83, 53, 82, 83, 26, 38,  7, 66, 59, 85, 28, 20],
       [99, 68, 25, 11, 28, 15, 62, 62, 46, 62, 37, 61],
       [97, 16, 98, 15,  6, 80, 25, 56, 87, 65,  2, 75],
       [48,  8, 18, 88, 94,  1, 23, 47, 63, 24, 27, 18],
       [96,  3,  3, 39, 16, 39, 89, 12, 82, 47, 56, 13],
       [96, 17, 42, 76, 74, 14, 14, 69, 68, 96, 81, 46],
       [49, 30, 24,  5, 77, 77, 71, 62, 36, 19, 15, 97],
       [39, 11, 19, 30, 94, 98, 81, 29, 75, 30, 90, 13],
       [47, 48, 19, 19, 49, 71, 55, 12, 39,  9, 24, 60],
       [71, 12, 92, 61,  8, 27, 67, 70, 56, 25, 65, 37]], dtype=int32)

In [74]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [76]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [77]:
type(b)

numpy.ndarray

In [78]:
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [79]:
b[:]

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [80]:
b[1:3]

array([[16, 14, 14, 19],
       [18, 15, 18, 15]], dtype=int32)

In [81]:
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [83]:
b[1,2]

np.int32(14)

In [84]:
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [85]:
b[1,3]

np.int32(19)

In [86]:
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [88]:
b[2:3]

array([[18, 15, 18, 15]], dtype=int32)

In [89]:
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [91]:
b[0:2]

array([[17, 16, 14, 19],
       [16, 14, 14, 19]], dtype=int32)

In [92]:
b[0:-2]

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15]], dtype=int32)

In [93]:
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [94]:
b[0,2]

np.int32(14)

In [95]:
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [96]:
b[-5:-3]

array([[17, 16, 14, 19],
       [16, 14, 14, 19]], dtype=int32)

In [97]:
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [98]:
b[-4:2]

array([[16, 14, 14, 19]], dtype=int32)

In [99]:
np.random.randint(10,20,(4,4))

array([[16, 17, 14, 12],
       [18, 18, 11, 13],
       [15, 11, 12, 15],
       [17, 10, 11, 13]], dtype=int32)

In [100]:
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [101]:
b[-4,-2]

np.int32(14)

In [102]:
b

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

In [103]:
b[-4:2] 

array([[16, 14, 14, 19]], dtype=int32)

In [104]:
b[:]

array([[17, 16, 14, 19],
       [16, 14, 14, 19],
       [18, 15, 18, 15],
       [17, 11, 11, 13],
       [19, 18, 16, 14]], dtype=int32)

# Operations

In [105]:
a = np.random.randint(10,20,10)
a

array([16, 17, 13, 18, 18, 13, 15, 13, 11, 11], dtype=int32)

In [106]:
id(a)

3165552580656

In [107]:
arr

array([0, 1, 2, 3, 4, 5])

In [108]:
arr2 = np.random.randint(0,100,(10,10))

In [109]:
arr2

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [84, 89, 80, 96, 31, 33, 98, 47, 57, 74],
       [64, 10, 80, 13, 79,  5, 46, 25, 16, 31]], dtype=int32)

In [112]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [113]:
arr

array([0, 1, 2, 3, 4, 5])

In [114]:
arr[:4] 

array([0, 1, 2, 3])

In [115]:
arr2[:]

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [84, 89, 80, 96, 31, 33, 98, 47, 57, 74],
       [64, 10, 80, 13, 79,  5, 46, 25, 16, 31]], dtype=int32)

In [116]:
arr2[0:5] 

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25]], dtype=int32)

In [117]:
arr2

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [84, 89, 80, 96, 31, 33, 98, 47, 57, 74],
       [64, 10, 80, 13, 79,  5, 46, 25, 16, 31]], dtype=int32)

In [118]:
arr2[1,4] 

np.int32(12)

In [119]:
arr2

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [84, 89, 80, 96, 31, 33, 98, 47, 57, 74],
       [64, 10, 80, 13, 79,  5, 46, 25, 16, 31]], dtype=int32)

In [120]:
arr2[-5,5] 

np.int32(63)

In [121]:
arr2[-5,-5] 

np.int32(63)

In [122]:
arr2

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [84, 89, 80, 96, 31, 33, 98, 47, 57, 74],
       [64, 10, 80, 13, 79,  5, 46, 25, 16, 31]], dtype=int32)

In [123]:
arr2[-1,-2]

np.int32(16)

In [124]:
arr2

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [84, 89, 80, 96, 31, 33, 98, 47, 57, 74],
       [64, 10, 80, 13, 79,  5, 46, 25, 16, 31]], dtype=int32)

In [125]:
arr2[::-1] # reverse 

array([[64, 10, 80, 13, 79,  5, 46, 25, 16, 31],
       [84, 89, 80, 96, 31, 33, 98, 47, 57, 74],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [68, 75, 91,  0, 14, 56, 81,  8, 74, 32]], dtype=int32)

In [126]:
arr2

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [84, 89, 80, 96, 31, 33, 98, 47, 57, 74],
       [64, 10, 80, 13, 79,  5, 46, 25, 16, 31]], dtype=int32)

In [128]:
arr2[::-2]

array([[64, 10, 80, 13, 79,  5, 46, 25, 16, 31],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36]], dtype=int32)

In [129]:
arr2

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [84, 89, 80, 96, 31, 33, 98, 47, 57, 74],
       [64, 10, 80, 13, 79,  5, 46, 25, 16, 31]], dtype=int32)

In [131]:
arr2[::-3]

array([[64, 10, 80, 13, 79,  5, 46, 25, 16, 31],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [68, 75, 91,  0, 14, 56, 81,  8, 74, 32]], dtype=int32)

In [132]:
arr2

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62],
       [22, 53, 81, 59, 66, 95, 51, 36, 45, 26],
       [84, 89, 80, 96, 31, 33, 98, 47, 57, 74],
       [64, 10, 80, 13, 79,  5, 46, 25, 16, 31]], dtype=int32)

In [133]:
arr2[:-3]

array([[68, 75, 91,  0, 14, 56, 81,  8, 74, 32],
       [12, 66, 78, 13, 12, 64,  7, 22, 79, 36],
       [38, 38, 95, 23, 38, 98, 42, 83, 82, 51],
       [99, 10,  2, 22, 65, 39, 29, 10, 92, 91],
       [12, 74, 34, 12, 36, 11, 61, 22,  6, 25],
       [13, 35,  7, 31, 28, 63, 75,  0, 20, 34],
       [27, 86, 15, 98, 91, 34, 45, 17, 61, 62]], dtype=int32)

In [134]:
arr

array([0, 1, 2, 3, 4, 5])

In [135]:
arr.max()

np.int64(5)

In [136]:
arr.min()

np.int64(0)

In [137]:
arr2.max()

np.int32(99)

In [138]:
arr2.min()

np.int32(0)

In [139]:
arr

array([0, 1, 2, 3, 4, 5])

In [140]:
arr.mean()

np.float64(2.5)

In [141]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [142]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# Without work on import* can you please find the median, mode

In [143]:
arr

array([0, 1, 2, 3, 4, 5])

In [144]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [145]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [146]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [147]:
arr

array([0, 1, 2, 3, 4, 5])

In [152]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [153]:
arr

array([0, 1, 2, 3, 4, 5])

In [154]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [155]:
arr.reshape(2,3,order='F') # print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [156]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [157]:
arr

array([0, 1, 2, 3, 4, 5])

In [158]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [159]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [160]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [161]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [162]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [164]:
arr.reshape(3,2) 

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing

In [165]:
mat = np.arange(0,100).reshape(10,10) 

In [166]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [167]:
row = 4
col = 5

In [168]:
col


5

In [169]:
row

4

In [170]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [171]:
mat[row,col]

np.int64(45)

In [173]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [174]:
mat[4,5] 

np.int64(45)

In [175]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
col =6

In [177]:
col

6

In [178]:
mat[6] #  befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [179]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [180]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [181]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [182]:
mat[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [183]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [185]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [186]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [187]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [188]:
row

4

In [189]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [190]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [191]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [195]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [196]:
mat[-1]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [197]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
row

4

In [199]:
col

6

In [200]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [201]:
mat[1,4]

np.int64(14)

In [202]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [204]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [205]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [207]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [208]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [209]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [210]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [215]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [218]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [219]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [220]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [222]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[0,1]

np.int64(1)

In [225]:
mat[1,6]

np.int64(16)

In [226]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [227]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [228]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [229]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [230]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [231]:
mat[3,5]

np.int64(35)

In [233]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
mat[1:2,2:4] 

array([[12, 13]])

In [235]:
mat[2:3,2:3] 

array([[22]])

In [236]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [237]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [238]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
mat[2:3,4:5]

array([[24]])

# Masking

In [240]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [241]:
id(mat)

3165579093520

In [242]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [243]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [244]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [246]:
mat [mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [247]:
mat[mat==50] 

array([50])

In [248]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [249]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [250]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [251]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [252]:
a4 = mat[mat==50]
a4

array([50])

 # Python program to generate otp

In [255]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp
    # Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")


Your OTP is: 2133


In [256]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [257]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [260]:
list1=['a','b','g',1,5]
print(list1.pop())

5


In [261]:
list1

['a', 'b', 'g', 1]

In [264]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]


In [265]:
y

[1, 2, 3]